<a href="https://colab.research.google.com/github/ranjeev3000/numpy-generate-vandermonde-matrix/blob/main/numpy-generate-vandermonde-matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.
'''

'\nWrite a function so that the columns of the output matrix are powers of the input\nvector.\nThe order of the powers is determined by the increasing boolean argument. Specifically, when\nincreasing is False, the i-th output column is the input vector raised element-wise to the power\nof N - i - 1.\n\nHINT: Such a matrix with a geometric progression in each row is named for Alexandre-\nTheophile Vandermonde.\n'

In [2]:
import numpy as np


In [5]:
x = np.array([1,2,3,4])

In [6]:
np.vander (x)

array([[ 1,  1,  1,  1],
       [ 8,  4,  2,  1],
       [27,  9,  3,  1],
       [64, 16,  4,  1]])

In [7]:
np.vander(x,increasing=True)

array([[ 1,  1,  1,  1],
       [ 1,  2,  4,  8],
       [ 1,  3,  9, 27],
       [ 1,  4, 16, 64]])

Now, as per the question, we have to raise every elements in the matrix to n-i-1.

In [9]:
def gen_vander_matrix(ipvector,n,increasing=False):

  if not increasing:
    op_matx = np.array([x**(n-i-1) for x in ipvector for i in range(n)]).reshape(ipvector.size,n)
  else:
    op_matx = 
    

In [12]:
print("------------OUTPUT-----------\n")

inputvector = np.array ([1,2,3,4,5])
no_col_opmatx = 3
op_matx_dec_order = gen_vander_matrix(inputvector, no_col_opmatx, False)
op_matx_inc_order = gen_vander_matrix(inputvector, no_col_opmatx, True)

print(f"The input array is : {inputvector}\n")
print(f"No. of columns on which matrix is reshaped is {no_col_opmatx}")
print(f"Vander matrix of the input array in decreasing order of powers:\n {op_matx_dec_order}")
print(f"Vander matrix of the input array in increasing order is : \n{op_matx_inc_order}")

------------OUTPUT-----------

The input array is : [1 2 3 4 5]

No. of columns on which matrix is reshaped is 3
Vander matrix of the input array in decreasing order of powers:
 [[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]
 [25  5  1]]
Vander matrix of the input array in increasing order is : 
[[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]
 [ 1  5 25]]
